### PR TITLE
remove dependency on project-management

### PR DESCRIPTION
**Pull request by ericsong**
Removes the dependency on https://github.com/dmohs/project-management to reduce the number of submodules and PRs that need to be made to make changes to our dev tooling.

The submodule was removed using `git rm utils` and restored by copying over the files.

### CODE REVIEW

**Review by als364 — APPROVED** [review]
Sweet. Thank you for doing this!

**Comment by als364** [comment]
Oh, actually, one note - can you please remove the bit about 'git submodule init' in the top level README and the comments about submodules in these files?

**Comment by ericsong** [comment]
oh! good catch. will do

**Comment by ericsong** [comment]
oops. I accidentally pushed the documentation changes to master so I'll just merge this in. I guess this repo doesn't prevent pushes to master.

**Pull request merged**
